name = "NumericalIntegration"
uuid = "d6140f40-64b2-11e9-1437-014cfcc810fe"
authors = ["dextorious"]
version = "0.3.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[extras]
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test","StaticArrays","InteractiveUtils","HCubature"]
