name = "NumericalIntegration"
uuid = "e7bfaba1-d571-5449-8927-abc22e82249b"
authors = ["dextorious"]
version = "0.3.3"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
Interpolations = "0.13, 0.14"
julia = "0.7, 1"

[extras]
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[targets]
test = ["Test", "InteractiveUtils", "StaticArrays", "HCubature", "Unitful"]
